---
- name: Install pip
  become: true
  apt:
    name: '{{ item }}'
    state: latest
  with_items: ['python3-venv', 'python3-pip']

- name: Install app dependencies
  become: true
  pip:
    requirements: /vagrant/requirements.txt
    executable: pip3